from PIL import Image, ImageFilter, ImageChops, ImageOps
from pathlib import Path
import shutil
path = Path('public/images/logo-site.png')
backup = path.with_name('logo-site-backup.png')
if not backup.exists():
    shutil.copy2(path, backup)
img = Image.open(path).convert('RGBA')
alpha = img.getchannel('A')
blur_alpha = alpha.filter(ImageFilter.GaussianBlur(radius=6))
edge_mask = ImageChops.subtract(blur_alpha, alpha)
emboss = img.filter(ImageFilter.EMBOSS)
embossed = Image.blend(img, emboss, 0.28)
highlight = Image.new('RGBA', img.size, (255, 238, 200, 0))
highlight_mask = edge_mask.point(lambda v: min(255, int(v * 1.6)))
highlight.putalpha(highlight_mask)
highlight = highlight.filter(ImageFilter.GaussianBlur(radius=2))
darken = Image.new('RGBA', img.size, (0, 0, 0, 0))
darken_mask = edge_mask.point(lambda v: min(255, int(v * 0.8)))
darken.putalpha(darken_mask)
darken = darken.filter(ImageFilter.GaussianBlur(radius=1.5))
outer_glow = Image.new('RGBA', img.size, (255, 255, 255, 0))
glow_mask = alpha.filter(ImageFilter.GaussianBlur(radius=12)).point(lambda v: int(v * 0.14))
outer_glow.putalpha(glow_mask)
result = Image.alpha_composite(embossed, highlight)
result = Image.alpha_composite(result, darken)
result = Image.alpha_composite(outer_glow, result)
result = Image.blend(result, ImageOps.autocontrast(result.convert('RGB')).convert('RGBA'), 0.1)
result.save(path)
print('Updated logo with bevel emboss and glow/darken effects. Backup saved to', backup)
