'use client'

import { useEffect, useMemo, useState } from 'react'
import { MapPin, Route, TrainFront, X } from 'lucide-react'
import { TOUR_PACKAGES } from '@/lib/tours-data'
import styles from './route-map-preview.module.css'

type VisualWaypoint = { uid: string; name: string; x: number; y: number; role: string; atlasPosition?: { x: number; y: number } }
type VisualRoute = { uid: string; start: string; end: string; lineType: string; trace: [number, number][] }
type VisualTrip = { waypoints: string[]; segments: string[]; visualRouteUids: string[] }
type Place = { name: string; lat: number; lon: number; display: string }
type VisualData = { imageWidth: number; imageHeight: number; waypoints: VisualWaypoint[]; routes: VisualRoute[]; tours: Record<string, VisualTrip>; places: Record<string, Place> }

const imageByPlace: Record<string, string> = { Sigiriya:'/images/journal/sunrise-over-the-lion-rock.jpg',Kandy:'/images/journal/a-night-at-the-temple-of-the-tooth.jpg','Nuwara Eliya':'/images/fine-lanka-journey-blue-lily-background.jpg',Ella:'/images/journal/the-slow-train-to-ella.jpg',Yala:'/images/journal/tracking-leopards-in-yala.jpg',Mirissa:'/images/journal/whales-before-breakfast.jpg',Galle:'/images/fine-lanka-explore-heritage-background.jpg','Arugam Bay':'/images/fine-lanka-arugam-bay-surf.jpg',Mannar:'/images/journal/following-the-ramayana-trail-to-mannar.jpg' }
const descriptions: Record<string, string> = { Airport:'Bandaranaike International Airport, the practical starting point for most island circuits.',Sigiriya:'The ancient Lion Rock fortress rises from the Cultural Triangle, surrounded by forest and village paths.',Kandy:'Sri Lanka’s hill capital, home to the Temple of the Sacred Tooth Relic and a lake-ringed old centre.','Nuwara Eliya':'Tea country in the central highlands, reached through winding roads and cloud-forest scenery.',Ella:'A compact hill town known for the Nine Arches Bridge, mountain walks and the railway corridor.',Yala:'A southeastern wildlife landscape where safari access roads branch from the main coastal corridor.',Mirissa:'A south-coast harbour town and a base for seasonal whale-watching excursions.',Galle:'A historic fortified port whose Dutch-era ramparts anchor the southern coastal route.','Arugam Bay':'A celebrated east-coast surf town on the dry-zone shoreline.',Mannar:'A remote northwestern island gateway known for baobabs, flamingos and Ramayana-linked sites.' }
const symbolByCategory: Record<string, string> = { arrival:'✈', beach:'◒', surf:'⌁', heritage:'✦', coral:'✺', tea:'❧', rail:'▰', rafting:'≈', mountains:'⌃', wildlife:'♢', waterfall:'≋', safari:'♞', whales:'◓' }
const categoryByPlace: Record<string, string> = { Airport:'arrival',Negombo:'beach',Kalpitiya:'surf',Mannar:'heritage',Jaffna:'heritage',Anuradhapura:'heritage',Trincomalee:'coral',Sigiriya:'heritage',Kandy:'heritage','Nuwara Eliya':'tea',Kitulgala:'rafting',Knuckles:'mountains',Meemure:'mountains',Haputale:'tea',Ella:'rail',Nallathanni:'mountains',"Adam's Peak":'mountains','Horton Plains':'wildlife',"Lipton's Seat":'tea',Diyaluma:'waterfall',Dunhinda:'waterfall',Yala:'safari',Udawalawe:'safari','Pasikudah':'coral','Arugam Bay':'surf',Tangalle:'beach',Mirissa:'whales',Galle:'heritage',Bentota:'beach',Unawatuna:'coral' }
function traceD(trace:[number,number][], w=1664, h=2080) { return trace.map(([x,y],i)=>`${i?'L':'M'} ${(x/w*100).toFixed(2)} ${(y/h*100).toFixed(2)}`).join(' ') }

export function RouteMapPreview() {
  const [data,setData]=useState<VisualData|null>(null)
  const [selectedSlug,setSelectedSlug]=useState(TOUR_PACKAGES[0].slug)
  const [selectedPlace,setSelectedPlace]=useState<string|null>(null)
  const [selectedMarkerUid,setSelectedMarkerUid]=useState<string|null>(null)
  const [error,setError]=useState<string|null>(null)
  useEffect(()=>{ fetch('/data/atlas-visual-data.json').then(r=>r.ok?r.json():Promise.reject(new Error('Visual atlas data could not be loaded.'))).then(setData).catch(e=>setError(e.message)) },[])
  const selectedTour=TOUR_PACKAGES.find(t=>t.slug===selectedSlug) ?? TOUR_PACKAGES[0]
  const selectedTrip=data?.tours[selectedSlug]
  const activeNames=useMemo(()=>new Set((selectedTrip?.waypoints ?? []).map(name=>name==='Airport'?'Bandaranaike Airport':name)),[selectedTrip])
  const activeRoutes=useMemo(()=>new Set(selectedTrip?.visualRouteUids ?? []),[selectedTrip])
  const place=data && selectedPlace ? data.places[selectedPlace] : null
  return <section className={styles.section}>
    <div className={styles.header}><div><p className={styles.kicker}>Destination atlas · computer-vision registered</p><h1>Follow the island <em>by feeling.</em></h1><p className={styles.lede}>The fixed atlas is the source of truth. Every visible waypoint and orange route trace is registered in image coordinates, then recoloured for the selected itinerary.</p></div><div className={styles.legend}><span><i className={styles.legendRouteActive}/> Selected trip</span><span><i className={styles.legendRouteQuiet}/> Other routes</span><span><i className={styles.legendDestination}/> Primary destination</span><span><i className={styles.legendHub}/> Hub / sub-point</span><span><TrainFront size={14}/> Rail option</span></div></div>
    <div className={styles.controls}><label htmlFor="route-select">Highlight a travel plan</label><select id="route-select" value={selectedSlug} onChange={e=>{setSelectedSlug(e.target.value);setSelectedPlace(null)}}>{TOUR_PACKAGES.map(t=><option key={t.slug} value={t.slug}>{t.name}</option>)}</select><div className={styles.routeSummary}><Route size={16}/><span>{selectedTour.route}</span></div></div>
    <div className={styles.mapShell}><div className={styles.mapCanvas}><img src="/images/fine-lanka-route-atlas-all-hubs.png" alt="Illustrated tourism map of Sri Lanka" className={styles.mapImage}/><svg className={styles.routeOverlay} viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Computer-vision registered route traces">{data?.routes.map(route=>{const d=traceD(route.trace,data.imageWidth,data.imageHeight);const active=activeRoutes.has(route.uid);return <g key={route.uid}>{active&&<path d={d} className={styles.activeHalo}/>}<path d={d} className={active?styles.activePath:styles.quietPath}/></g>})}</svg><div className={styles.markerLayer}>{data?.waypoints.map(w=>{const active=activeNames.has(w.name);const clicked=selectedMarkerUid===w.uid;const primary=w.role==='primary-tourism';const category=categoryByPlace[w.name] ?? 'heritage';return <button key={w.uid} type="button" className={`${styles.marker} ${primary?styles.primaryMarker:styles.hubMarker} ${active?styles.activeMarker:''} ${clicked?styles.clickedMarker:''}`} style={{left:`${w.x/16.64}%`,top:`${w.y/20.8}%`}} onClick={()=>{setSelectedPlace(w.name);setSelectedMarkerUid(w.uid)}} title={w.name} aria-label={`Open details for ${w.name}`}><span className={styles.markerArt}>{symbolByCategory[category] ?? '✦'}</span><span className={styles.markerLabel}>{w.name}</span></button>})}</div>{place && <aside className={styles.popup}><button type="button" onClick={()=>{setSelectedPlace(null);setSelectedMarkerUid(null)}} aria-label="Close place details"><X size={18}/></button><img src={imageByPlace[selectedPlace!] ?? '/images/sri-lanka-map-island-focus.jpg'} alt={selectedPlace!}/><p className={styles.popupKicker}>{activeNames.has(selectedPlace!)?'Selected itinerary destination':'Atlas waypoint'}</p><h2>{selectedPlace}</h2><p>{descriptions[selectedPlace!] ?? `${selectedPlace} is part of the fixed route atlas and can be reached through the displayed corridor.`}</p>{place && <div className={styles.popupMeta}><MapPin size={14}/>{place.lat.toFixed(4)}° N · {place.lon.toFixed(4)}° E</div>}</aside>}</div></div>
    {error && <p className={styles.error}>{error}</p>}<p className={styles.sourceNote}>The underlying map image is unchanged. The overlay is registered from the visible waypoint circles and orange/dashed line network identified by computer vision, with route traces kept in pixel coordinates.</p>
  </section>
}
