import json
from pathlib import Path

locations = [
    ('kankesanturai', 'Kankesanturai', 320, 110, 'coast', 'primary'),
    ('point-pedro', 'Point Pedro', 500, 55, 'coast', 'primary'),
    ('jaffna', 'Jaffna', 430, 120, 'heritage', 'primary'),
    ('nallur-kandaswamy-temple', 'Nallur Kandaswamy Temple', 510, 175, 'heritage', 'primary'),
    ('elephant-pass', 'Elephant Pass', 650, 250, 'landmark', 'hub'),
    ('kilinochchi', 'Kilinochchi', 560, 320, 'landmark', 'hub'),
    ('chundikulam', 'Chundikulam Bird Sanctuary', 780, 255, 'wildlife', 'primary'),
    ('mullaittivu', 'Mullaittivu', 960, 350, 'coast', 'primary'),
    ('mannar', 'Mannar', 395, 390, 'coast', 'primary'),
    ('madhu-road', 'Madhu Road National Park', 555, 475, 'wildlife', 'primary'),
    ('vavuniya', 'Vavuniya', 715, 525, 'landmark', 'hub'),
    ('kokkilai', 'Kokkilai Sanctuary', 970, 495, 'wildlife', 'primary'),
    ('pulmoddai', 'Pulmoddai', 1115, 560, 'coast', 'hub'),
    ('giant-tank', 'Giant Tank Sanctuary', 285, 650, 'wildlife', 'primary'),
    ('madhu-church', 'Madhu Church', 540, 610, 'heritage', 'primary'),
    ('wilpattu', 'Wilpattu National Park', 445, 820, 'wildlife', 'primary'),
    ('kalpitiya', 'Kalpitiya', 300, 945, 'coast', 'primary'),
    ('anuradhapura', 'Anuradhapura Ancient City', 575, 790, 'heritage', 'primary'),
    ('mihintale', 'Mihintale', 760, 660, 'heritage', 'primary'),
    ('aukana', 'Aukana', 835, 715, 'heritage', 'primary'),
    ('ritigala', 'Ritigala Mountain', 875, 785, 'mountain', 'primary'),
    ('trincomalee', 'Trincomalee', 1190, 710, 'coast', 'primary'),
    ('nilaveli', 'Nilaveli', 1250, 775, 'coast', 'primary'),
    ('pigeon-island', 'Pigeon Island', 1285, 820, 'coast', 'primary'),
    ('puttalam', 'Puttalam', 330, 1120, 'coast', 'hub'),
    ('yapahuwa', 'Yapahuwa Rock Fortress', 510, 1010, 'heritage', 'primary'),
    ('dambulla', 'Dambulla', 710, 1030, 'heritage', 'primary'),
    ('sigiriya', 'Sigiriya', 875, 970, 'heritage', 'primary'),
    ('habanara', 'Habarana', 810, 900, 'landmark', 'hub'),
    ('polonnaruwa', 'Polonnaruwa', 1060, 1020, 'heritage', 'primary'),
    ('minneriya', 'Minneriya National Park', 1080, 1110, 'wildlife', 'primary'),
    ('kaudulla', 'Kaudulla National Park', 1080, 1220, 'wildlife', 'primary'),
    ('pasikudah', 'Pasikudah Beach', 1390, 1080, 'coast', 'primary'),
    ('kurunegala', 'Kurunegala', 540, 1210, 'landmark', 'primary'),
    ('munneswaram', 'Munneswaram Kovil', 330, 1270, 'heritage', 'primary'),
    ('chilaw', 'Chilaw', 320, 1300, 'coast', 'hub'),
    ('alu-vihara', 'Alu Vihara', 760, 1360, 'heritage', 'primary'),
    ('matale', 'Matale', 760, 1305, 'heritage', 'primary'),
    ('maha-oya', 'Maha Oya', 1190, 1380, 'nature', 'hub'),
    ('maha-oya-reservoir', 'Maha Oya Reservoir', 1280, 1400, 'nature', 'hub'),
    ('wasgamuwa', 'Wasgamuwa National Park', 1120, 1300, 'wildlife', 'primary'),
    ('ma­hiyanganaya', 'Mahiyanganaya', 1120, 1325, 'heritage', 'primary'),
    ('dambana', 'Dambana', 1130, 1400, 'culture', 'primary'),
    ('batticaloa', 'Batticaloa', 1450, 1430, 'coast', 'primary'),
    ('kattankudy', 'Kattankudy', 1480, 1510, 'coast', 'hub'),
    ('kalmunai', 'Kalmunai', 1510, 1580, 'coast', 'hub'),
    ('ampara', 'Ampara', 1300, 1550, 'landmark', 'hub'),
    ('kandy', 'Kandy', 790, 1480, 'heritage', 'primary'),
    ('pinnawala', 'Pinnawala Elephant Orphanage', 520, 1490, 'wildlife', 'primary'),
    ('bandaranaike-airport', 'Bandaranaike International Airport', 355, 1580, 'arrival', 'primary'),
    ('negombo', 'Negombo', 350, 1480, 'coast', 'primary'),
    ('colombo', 'Colombo', 350, 1740, 'landmark', 'primary'),
    ('avissawella', 'Avissawella', 535, 1640, 'landmark', 'hub'),
    ('knuckles', 'Knuckles Mountain Range', 925, 1510, 'mountain', 'primary'),
    ('meemure', 'Meemure Village', 1015, 1575, 'mountain', 'primary'),
    ('gampola', 'Gampola', 710, 1540, 'landmark', 'hub'),
    ('nallathanni', 'Nallathanni', 820, 1660, 'mountain', 'primary'),
    ('adams-peak', "Adam's Peak", 760, 1740, 'mountain', 'primary'),
    ('ratnapura', 'Ratnapura', 620, 1850, 'landmark', 'hub'),
    ('nuwara-eliya', 'Nuwara Eliya', 850, 1750, 'tea', 'primary'),
    ('horton-plains', 'Horton Plains National Park', 770, 1840, 'mountain', 'primary'),
    ('haputale', 'Haputale', 900, 1900, 'mountain', 'primary'),
    ('badulla', 'Badulla', 1020, 1740, 'landmark', 'hub'),
    ('ella', 'Ella', 1055, 1870, 'mountain', 'primary'),
    ('ramboda', 'Ramboda Falls', 850, 1610, 'waterfall', 'primary'),
    ('victoria-falls', 'Victoria Falls Reservoir', 980, 1570, 'waterfall', 'primary'),
    ('dunhinda', 'Dunhinda Falls', 1120, 1745, 'waterfall', 'primary'),
    ('diyaluma', 'Diyaluma Falls', 1140, 1850, 'waterfall', 'primary'),
    ('wellawaya', 'Wellawaya', 1170, 1900, 'landmark', 'hub'),
    ('udawalawe', 'Udawalawe National Park', 850, 1980, 'wildlife', 'primary'),
    ('sinharaja', 'Sinharaja Rain Forest', 600, 1980, 'wildlife', 'primary'),
    ('bentota', 'Bentota', 430, 1930, 'coast', 'primary'),
    ('galle', 'Galle', 540, 2040, 'heritage', 'primary'),
    ('unawatuna', 'Unawatuna Beach', 600, 2080, 'coast', 'primary'),
    ('mirissa', 'Mirissa Beach', 880, 2080, 'coast', 'primary'),
    ('matara', 'Matara', 980, 2060, 'coast', 'hub'),
    ('tangalle', 'Tangalle', 1160, 2040, 'coast', 'primary'),
    ('tissamaharama', 'Tissamaharama', 1280, 1940, 'landmark', 'primary'),
    ('kataragama', 'Kataragama', 1310, 1880, 'heritage', 'primary'),
    ('yala', 'Yala National Park', 1400, 1790, 'wildlife', 'primary'),
    ('pottuvil', 'Pottuvil', 1530, 1600, 'coast', 'hub'),
    ('arugam-bay', 'Arugam Bay', 1560, 1510, 'coast', 'primary'),
    ('kumana', 'Kumana Bird Sanctuary', 1480, 1760, 'wildlife', 'primary'),
]

markers = []
for location_id, name, x, y, kind, marker_type in locations:
    markers.append({
        'id': location_id.replace('­', ''),
        'name': name,
        'x': x,
        'y': y,
        'type': marker_type,
        'kind': kind,
    })

output = {
    'image': '/images/fine-lanka-route-atlas-all-hubs.png',
    'width': 1664,
    'height': 2080,
    'calibration': 'fresh waypoint calibration from supplied Sri Lanka Tour Map image, 2026-09-02',
    'source': {
        'map': 'Supplied Sri Lanka Tour Map image; fresh visual waypoint extraction.',
        'routes': 'Routes intentionally removed; this preview is marker-only.',
        'itineraryRule': 'No legacy itinerary paths or route overlays are used.'
    },
    'networkStats': {
        'markerCount': len(markers),
        'edgeCount': 0,
        'primaryCount': sum(1 for marker in markers if marker['type'] == 'primary'),
        'hubCount': sum(1 for marker in markers if marker['type'] == 'hub'),
        'itineraryCount': 0,
        'connected': False,
    },
    'markers': markers,
    'segments': [],
    'itineraries': [],
}
Path('/home/ubuntu/fine-lanka-web/public/data/route-atlas.json').write_text(json.dumps(output, indent=2) + '\n')
print(f'Wrote {len(markers)} fresh markers')
